name: Build RecoverEasy

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - "app/**"
      - "**/*.kt"
      - "**/*.xml"
      - "build.gradle.kts"
      - "settings.gradle.kts"
      - ".github/workflows/build-apk.yml"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Install SDK packages
        run: |
          sdkmanager "platform-tools" "platforms;android-34" "build-tools;34.0.0" > /dev/null
          yes | sdkmanager --licenses > /dev/null

      - name: Build Debug APK
        uses: gradle/gradle-build-action@v3
        with:
          gradle-version: "8.9"
          arguments: assembleDebug

      - name: Package artifact
        run: |
          mkdir -p out
          cp app/build/outputs/apk/debug/app-debug.apk "out/app-debug-${{ github.run_number }}.apk"

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-${{ github.run_number }}
          path: out/*.apk
